export const events = [
  // --- JUDO ---
  {
    emoji: "🥋",
    sport: "Judo",
    date: "2026-01-17",
    time: "—",
    event: "Eesti Meistrivõistlused",
    location: "A. Le Coq Spordihoone",
    city: "Tartu",
    tickets: "—",
    federation: "https://www.judo.ee",
    federationName: "Judoliit",
  },
  {
    emoji: "🥋",
    sport: "Judo",
    date: "2026-01-10",
    time: "—",
    event: "ELVA OPEN — Karikasarja I etapp (Club Cup)",
    location: "Elva Spordihoone, Tartu mnt 3/1",
    city: "Elva",
    tickets: "—",
    federation: "https://www.judo.ee",
    federationName: "Judoliit",
  },

  // --- KARATE ---
  {
    emoji: "🥋",
    sport: "Karate",
    date: "2026-01-31",
    time: "10:00",
    event: "Edu-Do Cup 2026",
    location: "TalTech Sports Hall",
    city: "Tallinn",
    tickets: "—",
    federation: "https://karate.ee",
    federationName: "Karate Liit",
  },
  {
    emoji: "🥋",
    sport: "Karate",
    date: "2026-02-28",
    time: "—",
    event: "36. Tallinn Bulldog",
    location: "Kalevi Spordihall",
    city: "Tallinn",
    tickets: "—",
    federation: "https://karate.ee",
    federationName: "Karate Liit",
  },
  {
    emoji: "🥋",
    sport: "Karate",
    date: "2026-03-07",
    time: "10:00",
    event: "Eesti Meistrivõistlused ja Esivõistlused Karates 2026",
    location: "—",
    city: "—",
    tickets: "—",
    federation: "https://karate.ee",
    federationName: "Karate Liit",
  },
  {
    emoji: "🥋",
    sport: "Karate",
    date: "2026-04-10",
    time: "15:00",
    event: "Põhjamaade Meistrivõistlused 2026",
    location: "A. Le Coq Spordimaja",
    city: "Tartu",
    tickets: "—",
    federation: "https://karate.ee",
    federationName: "Karate Liit",
  },

  // --- MAADLUS ---
  {
    emoji: "🤼",
    sport: "Maadlus",
    date: "2026-01-17",
    time: "—",
    event: "45. Avo Talpase mälestusvõistlused (Kreeka-rooma)",
    location: "—",
    city: "Kohtla-Järve",
    tickets: "—",
    federation: "https://maadlus.ee",
    federationName: "Maadlusliit",
  },
  {
    emoji: "🤼",
    sport: "Maadlus",
    date: "2026-01-18",
    time: "—",
    event: "Kuldkaruke 2026 (Vabamaadlus)",
    location: "Kohtla-Järve Spordikeskus, Järveküla tee 44",
    city: "Kohtla-Järve",
    tickets: "—",
    federation: "https://maadlus.ee",
    federationName: "Maadlusliit",
  },
  {
    emoji: "🤼",
    sport: "Maadlus",
    date: "2026-01-24",
    time: "—",
    event: "Täiskasvanute Eesti meistrivõistlused (GR · VM · NM)",
    location: "—",
    city: "Viljandi",
    tickets: "—",
    federation: "https://maadlus.ee",
    federationName: "Maadlusliit",
  },
  {
    emoji: "🤼",
    sport: "Maadlus",
    date: "2026-01-25",
    time: "—",
    event: "U15 Eesti meistrivõistlused (GR · VM · NM)",
    location: "—",
    city: "Viljandi",
    tickets: "—",
    federation: "https://maadlus.ee",
    federationName: "Maadlusliit",
  },
  {
    emoji: "🤼",
    sport: "Maadlus",
    date: "2026-03-07",
    time: "—",
    event: "U17 Eesti meistrivõistlused (GR · VM · NM)",
    location: "—",
    city: "Valga",
    tickets: "—",
    federation: "https://maadlus.ee",
    federationName: "Maadlusliit",
  },
  {
  emoji: "🤺",
  sport: "Fencing",
  date: "2025-12-14",
  time: "—",
  event: "U10 Open Draakon Cup",
  location: "Tallinn",
  city: "Tallinn",
  tickets: "—",
  federation: { name: "Vehklemisliit", link: "https://www.fencing.ee" },
},

{
  emoji: "🤺",
  sport: "Fencing",
  date: "2025-12-20",
  time: "—",
  event: "U17 Eesti Karikavõistlused",
  location: "Saku",
  city: "Saku",
  tickets: "—",
  federation: { name: "Vehklemisliit", link: "https://www.fencing.ee" },
},

{
  emoji: "🤺",
  sport: "Fencing",
  date: "2026-01-10",
  time: "—",
  event: "U17 Eesti Meistrivõistlused",
  location: "Saku",
  city: "Saku",
  tickets: "—",
  federation: { name: "Vehklemisliit", link: "https://www.fencing.ee" },
},
{
  emoji: "🤺",
  sport: "Fencing",
  date: "2026-01-17",
  time: "—",
  event: "U17 Baltic Cup III etapp",
  location: "Tartu",
  city: "Tartu",
  tickets: "—",
  federation: { name: "Vehklemisliit", link: "https://www.fencing.ee" },
},

{
  emoji: "🤺",
  sport: "Fencing",
  date: "2026-01-18",
  time: "—",
  event: "U20 Baltic Cup III etapp",
  location: "Tartu",
  city: "Tartu",
  tickets: "—",
  federation: { name: "Vehklemisliit", link: "https://www.fencing.ee" },
},

{
  emoji: "🤺",
  sport: "Fencing",
  date: "2026-01-24",
  time: "—",
  event: "U20 Eesti Meistrivõistlused",
  location: "Saku",
  city: "Saku",
  tickets: "—",
  federation: { name: "Vehklemisliit", link: "https://www.fencing.ee" },
},

{
  emoji: "🤺",
  sport: "Fencing",
  date: "2026-04-25",
  time: "—",
  event: "Eesti Meistrivõistlused",
  location: "Saku",
  city: "Saku",
  tickets: "—",
  federation: { name: "Vehklemisliit", link: "https://www.fencing.ee" },
},

{
  emoji: "🤺",
  sport: "Fencing",
  date: "2026-05-09",
  time: "—",
  event: "U23 Eesti Meistrivõistlused",
  location: "Saku",
  city: "Saku",
  tickets: "—",
  federation: { name: "Vehklemisliit", link: "https://www.fencing.ee" },
},

{
  emoji: "🤺",
  sport: "Fencing",
  date: "2026-05-16",
  time: "—",
  event: "U12 Eesti Meistrivõistlused",
  location: "—",
  city: "—",
  tickets: "—",
  federation: { name: "Vehklemisliit", link: "https://www.fencing.ee" },
}
];

export default events;